create table "public"."onramp" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "requestUrl" text,
    "responseData" json
);


alter table "public"."onramp" enable row level security;

CREATE UNIQUE INDEX onramp_pkey ON public.onramp USING btree (id);

alter table "public"."onramp" add constraint "onramp_pkey" PRIMARY KEY using index "onramp_pkey";


